In [ ]:
#Machine Learning Model

LinearRegression

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("insurance.csv")

In [ ]:
df.head(4)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061

In [ ]:
#df.isnull().sum()

In [ ]:
df = pd.get_dummies(df, columns = ["sex", "smoker", "region"], dtype=int)

In [ ]:
df.head(4)

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,1,0,0,1,0,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0,0,0,1,0
2,28,33.000,3,4449.46200,0,1,1,0,0,0,1,0
3,33,22.705,0,21984.47061,0,1,1,0,0,1,0,0

In [ ]:
# linear regresion works when target column is numerical

In [ ]:
x =df.drop(columns=['charges'] )
y=df['charges']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr =LinearRegression()

In [ ]:
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,y_pred)

0.7835929767120722

In [131]:
# second data

In [132]:
df =pd.read_csv("tip.csv")

In [133]:
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [134]:
from sklearn.linear_model import LinearRegression

In [135]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [136]:
x =df.drop(columns=['total_bill'])
y=df['total_bill']

In [137]:
df =pd.get_dummies(df,columns=['sex','smoker','day','time'],dtype =int)

In [138]:
x = df.drop(columns=['total_bill', 'tip'])
y = df['total_bill']

In [139]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [140]:
df.head()

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,1,0,1,0,0,0,1,0,1,0
1,10.34,1.66,3,0,1,1,0,0,0,1,0,1,0
2,21.01,3.50,3,0,1,1,0,0,0,1,0,1,0
3,23.68,3.31,2,0,1,1,0,0,0,1,0,1,0
4,24.59,3.61,4,1,0,1,0,0,0,1,0,1,0

In [141]:
from sklearn.model_selection import train_test_split

In [142]:
x_train,x_test, y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [143]:
lr =LinearRegression()

In [144]:
lr.fit(x_train,y_train)

LinearRegression()

In [146]:
y_pred =lr.predict(x_test)

In [147]:
from sklearn.metrics import r2_score

In [148]:
r2_score(y_test,y_pred)

0.4308067469568859