In [1]:
import numpy as np
import pandas as pd

In [3]:
df =pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [9]:
x= df.drop(columns = ["has_covid"])
y= df["has_covid"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
# define the columns that need to be processed
categorical_features = ['gender','city']
numeric_features = ['age','fever']

In [16]:

#create transformer
numeric_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])


#combine transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num',numeric_transformer,numeric_features),
        ('cat',categorical_transformer,categorical_features)
    ]
)



#create the pipeline
clf = Pipeline(steps=[('preprocessor',preprocessor),
                      ('classifier',LogisticRegression())])

#train the model
clf.fit(x_train,y_train)

#evaluate the model
y_pred =clf.predict(x_test)

In [17]:
#y_pred

In [18]:
from sklearn.metrics import accuracy_score

In [20]:
acc =accuracy_score(y_test,y_pred)

In [21]:
acc

0.65

In [22]:
# second daata

In [38]:
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [31]:
df= pd.read_csv("/content/Social_Network_Ads - Social_Network_Ads.csv")

In [32]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [33]:
df = df.drop(columns = ["User ID","Gender"])

In [34]:
y = df["Purchased"]
x = df.drop(columns = ["Purchased"], axis =1)

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [46]:
pipe =Pipeline([
    ('scaler',StandardScaler()),
    ('pca',PCA(n_components=2)),
    ('classifier',RandomForestClassifier(n_estimators =100,random_state =42))
])

In [47]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [48]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [49]:
y_pred =pipe.predict(x_test)

In [50]:
acc =accuracy_score(y_test,y_pred)

In [51]:
print(acc)

0.8875